import minibig_jmx_engine as mje

def get_hb_ugi(jsonbeansdata,hostsource,epoch_time):
    ugi_pointer_id = mje.get_metricscategory_position(jsonbeansdata, 'Hadoop:service=HBase,name=UgiMetrics')
    print hostsource+" hb_ugi_LoginSuccessNumOps "+str(epoch_time)+" "+str(jsonbeansdata[ugi_pointer_id].get('LoginSuccessNumOps'))
    print hostsource+" hb_ugi_LoginFailureNumOps "+str(epoch_time)+" "+str(jsonbeansdata[ugi_pointer_id].get('LoginFailureNumOps'))

def get_hb_jvm(jsonbeansdata,hostsource,epoch_time):
    pointer_id = mje.get_metricscategory_position(jsonbeansdata, 'Hadoop:service=HBase,name=JvmMetrics')
    print hostsource+" hb_jvm_MemNonHeapUsedM "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('MemNonHeapUsedM'))
    print hostsource+" hb_jvm_MemNonHeapCommittedM "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('MemNonHeapCommittedM'))
    print hostsource+" hb_jvm_MemHeapUsedM "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('MemHeapUsedM'))
    print hostsource+" hb_jvm_MemHeapCommittedM "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('MemHeapCommittedM'))
    print hostsource+" hb_jvm_MemMaxM "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('MemMaxM'))
    print hostsource+" hb_jvm_GcCountParNew "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('GcCountParNew'))
    print hostsource+" hb_jvm_GcTimeMillisParNew "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('GcTimeMillisParNew'))
    print hostsource+" hb_jvm_GcCountConcurrentMarkSweep "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('GcCountConcurrentMarkSweep'))
    print hostsource+" hb_jvm_GcTimeMillisConcurrentMarkSweep "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('GcTimeMillisConcurrentMarkSweep'))
    print hostsource+" hb_jvm_GcCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('GcCount'))
    print hostsource+" hb_jvm_GcTimeMillis "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('GcTimeMillis'))
    print hostsource+" hb_jvm_ThreadsNew "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ThreadsNew'))
    print hostsource+" hb_jvm_ThreadsRunnable "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ThreadsRunnable'))
    print hostsource+" hb_jvm_ThreadsBlocked "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ThreadsBlocked'))
    print hostsource+" hb_jvm_ThreadsWaiting "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ThreadsWaiting'))
    print hostsource+" hb_jvm_ThreadsTimedWaiting "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ThreadsTimedWaiting'))
    print hostsource+" hb_jvm_ThreadsTerminated "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ThreadsTerminated'))
    print hostsource+" hb_jvm_LogFatal "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('LogFatal'))
    print hostsource+" hb_jvm_LogError "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('LogError'))
    print hostsource+" hb_jvm_LogWarn "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('LogWarn'))
    print hostsource+" hb_jvm_LogInfo "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('LogInfo'))

def get_hb_sys(jsonbeansdata,hostsource,epoch_time):
    pointer_id = mje.get_metricscategory_position(jsonbeansdata, 'Hadoop:service=HBase,name=MetricsSystem,sub=Stats')
    print hostsource+" hb_sys_NumActiveSources "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('NumActiveSources'))
    print hostsource+" hb_sys_NumAllSources "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('NumAllSources'))
    print hostsource+" hb_sys_NumActiveSinks "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('NumActiveSinks'))
    print hostsource+" hb_sys_NumAllSinks "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('NumAllSinks'))
    print hostsource+" hb_sys_SnapshotNumOps "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('SnapshotNumOps'))
    print hostsource+" hb_sys_SnapshotAvgTime "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('SnapshotAvgTime'))
    print hostsource+" hb_sys_PublishNumOps "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('PublishNumOps'))
    print hostsource+" hb_sys_PublishAvgTime "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('PublishAvgTime'))
    print hostsource+" hb_sys_DroppedPubAll "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('DroppedPubAll'))

def get_hb_ipc(jsonbeansdata,hostsource,epoch_time):
    pointer_id = mje.get_metricscategory_position(jsonbeansdata, 'Hadoop:service=HBase,name=IPC,sub=IPC')
    print hostsource+" hb_ipc_queueSize "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('queueSize'))
    print hostsource+" hb_ipc_numCallsInGeneralQueue "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('numCallsInGeneralQueue'))
    print hostsource+" hb_ipc_numCallsInReplicationQueue "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('numCallsInReplicationQueue'))
    print hostsource+" hb_ipc_numCallsInPriorityQueue "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('numCallsInPriorityQueue'))
    print hostsource+" hb_ipc_numOpenConnections "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('numOpenConnections'))
    print hostsource+" hb_ipc_numActiveHandler "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('numActiveHandler'))
    print hostsource+" hb_ipc_TotalCallTime_num_ops "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('TotalCallTime_num_ops'))
    print hostsource+" hb_ipc_TotalCallTime_min "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('TotalCallTime_min'))
    print hostsource+" hb_ipc_TotalCallTime_max "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('TotalCallTime_max'))
    print hostsource+" hb_ipc_TotalCallTime_mean "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('TotalCallTime_mean'))
    print hostsource+" hb_ipc_TotalCallTime_median "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('TotalCallTime_median'))
    print hostsource+" hb_ipc_exceptions.FailedSanityCheckException "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('exceptions.FailedSanityCheckException'))
    print hostsource+" hb_ipc_exceptions.RegionMovedException "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('exceptions.RegionMovedException'))
    print hostsource+" hb_ipc_QueueCallTime_num_ops "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('QueueCallTime_num_ops'))
    print hostsource+" hb_ipc_QueueCallTime_min "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('QueueCallTime_min'))
    print hostsource+" hb_ipc_QueueCallTime_max "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('QueueCallTime_max'))
    print hostsource+" hb_ipc_QueueCallTime_mean "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('QueueCallTime_mean'))
    print hostsource+" hb_ipc_QueueCallTime_median "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('QueueCallTime_median'))
    print hostsource+" hb_ipc_authenticationFailures "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('authenticationFailures'))
    print hostsource+" hb_ipc_authorizationFailures "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('authorizationFailures'))
    print hostsource+" hb_ipc_exceptions "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('exceptions'))
    print hostsource+" hb_ipc_RequestSize_num_ops "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('RequestSize_num_ops'))
    print hostsource+" hb_ipc_RequestSize_min "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('RequestSize_min'))
    print hostsource+" hb_ipc_RequestSize_max "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('RequestSize_max'))
    print hostsource+" hb_ipc_RequestSize_mean "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('RequestSize_mean'))
    print hostsource+" hb_ipc_RequestSize_median "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('RequestSize_median'))
    print hostsource+" hb_ipc_ResponseSize_num_ops "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ResponseSize_num_ops'))
    print hostsource+" hb_ipc_ResponseSize_min "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ResponseSize_min'))
    print hostsource+" hb_ipc_ResponseSize_max "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ResponseSize_max'))
    print hostsource+" hb_ipc_ResponseSize_mean "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ResponseSize_mean'))
    print hostsource+" hb_ipc_ResponseSize_median "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ResponseSize_median'))
    print hostsource+" hb_ipc_authenticationSuccesses "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('authenticationSuccesses'))
    print hostsource+" hb_ipc_authorizationSuccesses "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('authorizationSuccesses'))
    print hostsource+" hb_ipc_ProcessCallTime_num_ops "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ProcessCallTime_num_ops'))
    print hostsource+" hb_ipc_ProcessCallTime_min "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ProcessCallTime_min'))
    print hostsource+" hb_ipc_ProcessCallTime_max "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ProcessCallTime_max'))
    print hostsource+" hb_ipc_ProcessCallTime_mean "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ProcessCallTime_mean'))
    print hostsource+" hb_ipc_ProcessCallTime_median "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ProcessCallTime_median'))
    print hostsource+" hb_ipc_exceptions.NotServingRegionException "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('exceptions.NotServingRegionException'))
    print hostsource+" hb_ipc_sentBytes "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('sentBytes'))
    print hostsource+" hb_ipc_exceptions.RegionTooBusyException "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('exceptions.RegionTooBusyException'))
    print hostsource+" hb_ipc_receivedBytes "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('receivedBytes'))
    print hostsource+" hb_ipc_exceptions.OutOfOrderScannerNextException "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('exceptions.OutOfOrderScannerNextException'))
    print hostsource+" hb_ipc_exceptions.UnknownScannerException "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('exceptions.UnknownScannerException'))
