import minibig_jmx_engine as mje

def get_dn_status(xbeans,hostsource,epoch_time):
	pointer_id = get_metricscategory_position(xbeans, 'Hadoop:service=DataNode,name=DataNodeStatus')
	print hostsource+" dn_status_State "+str(epoch_time)+" "+str(xbeans[pointer_id].get('State'))
	print hostsource+" dn_status_SecurityEnabled "+str(epoch_time)+" "+str(xbeans[pointer_id].get('SecurityEnabled'))
	print hostsource+" dn_status_LastHATransitionTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('LastHATransitionTime'))
	print hostsource+" dn_status_HostAndPort "+str(epoch_time)+" "+str(xbeans[pointer_id].get('HostAndPort'))


def get_dn_rpc(xbeans,hostsource,epoch_time):
	pointer_id = get_metricscategory_position(xbeans, 'Hadoop:service=DataNode,name=RpcActivityForPort8020')
	print hostsource+" dn_rpc_SentBytes "+str(epoch_time)+" "+str(xbeans[pointer_id].get('SentBytes'))
	print hostsource+" dn_rpc_ReceivedBytes "+str(epoch_time)+" "+str(xbeans[pointer_id].get('ReceivedBytes'))
	print hostsource+" dn_rpc_RpcQueueTimeNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RpcQueueTimeNumOps'))
	print hostsource+" dn_rpc_RpcQueueTimeAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RpcQueueTimeAvgTime'))
	print hostsource+" dn_rpc_RpcProcessingTimeNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RpcProcessingTimeNumOps'))
	print hostsource+" dn_rpc_RpcProcessingTimeAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RpcProcessingTimeAvgTime'))
	print hostsource+" dn_rpc_RpcAuthenticationFailures "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RpcAuthenticationFailures'))
	print hostsource+" dn_rpc_RpcAuthenticationSuccesses "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RpcAuthenticationSuccesses'))
	print hostsource+" dn_rpc_RpcAuthorizationFailures "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RpcAuthorizationFailures'))
	print hostsource+" dn_rpc_RpcAuthorizationSuccesses "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RpcAuthorizationSuccesses'))
	print hostsource+" dn_rpc_NumOpenCodnections "+str(epoch_time)+" "+str(xbeans[pointer_id].get('NumOpenCodnections'))
	print hostsource+" dn_rpc_CallQueueLength "+str(epoch_time)+" "+str(xbeans[pointer_id].get('CallQueueLength'))
	pointer_id = get_metricscategory_position(xbeans, 'Hadoop:service=DataNode,name=RpcDetailedActivityForPort8020')
	print hostsource+" dn_rpc_VersionRequestNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('VersionRequestNumOps'))
	print hostsource+" dn_rpc_VersionRequestAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('VersionRequestAvgTime'))
	print hostsource+" dn_rpc_RegisterDatanodeNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RegisterDatanodeNumOps'))
	print hostsource+" dn_rpc_RegisterDatanodeAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RegisterDatanodeAvgTime'))
	print hostsource+" dn_rpc_SendHeartbeatNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('SendHeartbeatNumOps'))
	print hostsource+" dn_rpc_SendHeartbeatAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('SendHeartbeatAvgTime'))
	print hostsource+" dn_rpc_BlockReportNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('BlockReportNumOps'))
	print hostsource+" dn_rpc_BlockReportAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('BlockReportAvgTime'))

def get_dn_ugi(xbeans,hostsource,epoch_time):
	dn_ugi_pointer_id = get_metricscategory_position(xbeans, 'Hadoop:service=DataNode,name=UgiMetrics')
	print hostsource+" dn_ugi_LoginSuccessNumOps "+str(epoch_time)+" "+str(xbeans[dn_ugi_pointer_id].get('LoginSuccessNumOps'))
	print hostsource+" dn_ugi_LoginSuccessAvgTime "+str(epoch_time)+" "+str(xbeans[dn_ugi_pointer_id].get('LoginSuccessAvgTime'))
	print hostsource+" dn_ugi_LoginFailureNumOps "+str(epoch_time)+" "+str(xbeans[dn_ugi_pointer_id].get('LoginFailureNumOps'))
	print hostsource+" dn_ugi_LoginFailureAvgTime "+str(epoch_time)+" "+str(xbeans[dn_ugi_pointer_id].get('LoginFailureAvgTime'))
	print hostsource+" dn_ugi_tag.Hostname "+str(epoch_time)+" "+str(xbeans[dn_ugi_pointer_id].get('tag.Hostname'))
	print hostsource+" dn_ugi_GetGroupsNumOps "+str(epoch_time)+" "+str(xbeans[dn_ugi_pointer_id].get('GetGroupsNumOps'))
	print hostsource+" dn_ugi_GetGroupsAvgTime "+str(epoch_time)+" "+str(xbeans[dn_ugi_pointer_id].get('GetGroupsAvgTime'))

def get_dn_jvm(xbeans,hostsource,epoch_time):
	pointer_id = get_metricscategory_position(xbeans, 'Hadoop:service=DataNode,name=JvmMetrics')
	try:
		print hostsource+" dn_jvm_MemNonHeapUsedM "+str(epoch_time)+" "+str(xbeans[pointer_id].get('MemNonHeapUsedM'))
		print hostsource+" dn_jvm_MemNonHeapCommittedM "+str(epoch_time)+" "+str(xbeans[pointer_id].get('MemNonHeapCommittedM'))
		print hostsource+" dn_jvm_MemHeapUsedM "+str(epoch_time)+" "+str(xbeans[pointer_id].get('MemHeapUsedM'))
		print hostsource+" dn_jvm_MemHeapCommittedM "+str(epoch_time)+" "+str(xbeans[pointer_id].get('MemHeapCommittedM'))
		print hostsource+" dn_jvm_MemMaxM "+str(epoch_time)+" "+str(xbeans[pointer_id].get('MemMaxM'))
		print hostsource+" dn_jvm_GcCountParNew "+str(epoch_time)+" "+str(xbeans[pointer_id].get('GcCountParNew'))
		print hostsource+" dn_jvm_GcTimeMillisParNew "+str(epoch_time)+" "+str(xbeans[pointer_id].get('GcTimeMillisParNew'))
		print hostsource+" dn_jvm_GcCountConcurrentMarkSweep "+str(epoch_time)+" "+str(xbeans[pointer_id].get('GcCountConcurrentMarkSweep'))
		print hostsource+" dn_jvm_GcTimeMillisConcurrentMarkSweep "+str(epoch_time)+" "+str(xbeans[pointer_id].get('GcTimeMillisConcurrentMarkSweep'))
		print hostsource+" dn_jvm_GcCount "+str(epoch_time)+" "+str(xbeans[pointer_id].get('GcCount'))
		print hostsource+" dn_jvm_GcTimeMillis "+str(epoch_time)+" "+str(xbeans[pointer_id].get('GcTimeMillis'))
		print hostsource+" dn_jvm_ThreadsNew "+str(epoch_time)+" "+str(xbeans[pointer_id].get('ThreadsNew'))
		print hostsource+" dn_jvm_ThreadsRudnable "+str(epoch_time)+" "+str(xbeans[pointer_id].get('ThreadsRudnable'))
		print hostsource+" dn_jvm_ThreadsBlocked "+str(epoch_time)+" "+str(xbeans[pointer_id].get('ThreadsBlocked'))
		print hostsource+" dn_jvm_ThreadsWaiting "+str(epoch_time)+" "+str(xbeans[pointer_id].get('ThreadsWaiting'))
		print hostsource+" dn_jvm_ThreadsTimedWaiting "+str(epoch_time)+" "+str(xbeans[pointer_id].get('ThreadsTimedWaiting'))
		print hostsource+" dn_jvm_ThreadsTerminated "+str(epoch_time)+" "+str(xbeans[pointer_id].get('ThreadsTerminated'))
		print hostsource+" dn_jvm_LogFatal "+str(epoch_time)+" "+str(xbeans[pointer_id].get('LogFatal'))
		print hostsource+" dn_jvm_LogError "+str(epoch_time)+" "+str(xbeans[pointer_id].get('LogError'))
		print hostsource+" dn_jvm_LogWarn "+str(epoch_time)+" "+str(xbeans[pointer_id].get('LogWarn'))
		print hostsource+" dn_jvm_LogInfo "+str(epoch_time)+" "+str(xbeans[pointer_id].get('LogInfo'))
	except IndexError:
		x=0
	else:
		x=0

def get_dn_fsnamesys(xbeans,hostsource,epoch_time):
	pointer_id = get_metricscategory_position(xbeans, 'Hadoop:service=DataNode,name=FSNamesystemState')
	print hostsource+" dn_fsnamesys_CapacityTotal "+str(epoch_time)+" "+str(xbeans[pointer_id].get('CapacityTotal'))
	print hostsource+" dn_fsnamesys_CapacityUsed "+str(epoch_time)+" "+str(xbeans[pointer_id].get('CapacityUsed'))
	print hostsource+" dn_fsnamesys_CapacityRemaining "+str(epoch_time)+" "+str(xbeans[pointer_id].get('CapacityRemaining'))
	print hostsource+" dn_fsnamesys_TotalLoad "+str(epoch_time)+" "+str(xbeans[pointer_id].get('TotalLoad'))
	print hostsource+" dn_fsnamesys_BlocksTotal "+str(epoch_time)+" "+str(xbeans[pointer_id].get('BlocksTotal'))
	print hostsource+" dn_fsnamesys_MaxObjects "+str(epoch_time)+" "+str(xbeans[pointer_id].get('MaxObjects'))
	print hostsource+" dn_fsnamesys_FilesTotal "+str(epoch_time)+" "+str(xbeans[pointer_id].get('FilesTotal'))
	print hostsource+" dn_fsnamesys_PendingReplicationBlocks "+str(epoch_time)+" "+str(xbeans[pointer_id].get('PendingReplicationBlocks'))
	print hostsource+" dn_fsnamesys_UnderReplicatedBlocks "+str(epoch_time)+" "+str(xbeans[pointer_id].get('UnderReplicatedBlocks'))
	print hostsource+" dn_fsnamesys_ScheduledReplicationBlocks "+str(epoch_time)+" "+str(xbeans[pointer_id].get('ScheduledReplicationBlocks'))
	print hostsource+" dn_fsnamesys_PendingDeletionBlocks "+str(epoch_time)+" "+str(xbeans[pointer_id].get('PendingDeletionBlocks'))
	print hostsource+" dn_fsnamesys_BlockDeletionStartTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('BlockDeletionStartTime'))
	print hostsource+" dn_fsnamesys_FSState "+str(epoch_time)+" "+str(xbeans[pointer_id].get('FSState'))
	print hostsource+" dn_fsnamesys_NumLiveDataNodes "+str(epoch_time)+" "+str(xbeans[pointer_id].get('NumLiveDataNodes'))
	print hostsource+" dn_fsnamesys_NumDeadDataNodes "+str(epoch_time)+" "+str(xbeans[pointer_id].get('NumDeadDataNodes'))
	print hostsource+" dn_fsnamesys_NumDecomLiveDataNodes "+str(epoch_time)+" "+str(xbeans[pointer_id].get('NumDecomLiveDataNodes'))
	print hostsource+" dn_fsnamesys_NumDecomDeadDataNodes "+str(epoch_time)+" "+str(xbeans[pointer_id].get('NumDecomDeadDataNodes'))
	print hostsource+" dn_fsnamesys_VolumeFailuresTotal "+str(epoch_time)+" "+str(xbeans[pointer_id].get('VolumeFailuresTotal'))
	print hostsource+" dn_fsnamesys_EstimatedCapacityLostTotal "+str(epoch_time)+" "+str(xbeans[pointer_id].get('EstimatedCapacityLostTotal'))
	print hostsource+" dn_fsnamesys_NumDecommissioningDataNodes "+str(epoch_time)+" "+str(xbeans[pointer_id].get('NumDecommissioningDataNodes'))
	print hostsource+" dn_fsnamesys_NumStaleDataNodes "+str(epoch_time)+" "+str(xbeans[pointer_id].get('NumStaleDataNodes'))
	print hostsource+" dn_fsnamesys_NumStaleStorages "+str(epoch_time)+" "+str(xbeans[pointer_id].get('NumStaleStorages'))
	pointer_id = get_metricscategory_position(xbeans, 'Hadoop:service=DataNode,name=FSNamesystem')
	print hostsource+" dn_fsnamesys_MissingBlocks "+str(epoch_time)+" "+str(xbeans[pointer_id].get('MissingBlocks'))
	print hostsource+" dn_fsnamesys_MissingReplOneBlocks "+str(epoch_time)+" "+str(xbeans[pointer_id].get('MissingReplOneBlocks'))
	print hostsource+" dn_fsnamesys_ExpiredHeartbeats "+str(epoch_time)+" "+str(xbeans[pointer_id].get('ExpiredHeartbeats'))
	print hostsource+" dn_fsnamesys_TransactionsSinceLastCheckpoint "+str(epoch_time)+" "+str(xbeans[pointer_id].get('TransactionsSinceLastCheckpoint'))
	print hostsource+" dn_fsnamesys_TransactionsSinceLastLogRoll "+str(epoch_time)+" "+str(xbeans[pointer_id].get('TransactionsSinceLastLogRoll'))
	print hostsource+" dn_fsnamesys_LastCheckpointTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('LastCheckpointTime'))
	print hostsource+" dn_fsnamesys_CapacityTotalGB "+str(epoch_time)+" "+str(xbeans[pointer_id].get('CapacityTotalGB'))
	print hostsource+" dn_fsnamesys_CapacityUsedGB "+str(epoch_time)+" "+str(xbeans[pointer_id].get('CapacityUsedGB'))
	print hostsource+" dn_fsnamesys_CapacityRemainingGB "+str(epoch_time)+" "+str(xbeans[pointer_id].get('CapacityRemainingGB'))
	print hostsource+" dn_fsnamesys_CapacityUsedNonDFS "+str(epoch_time)+" "+str(xbeans[pointer_id].get('CapacityUsedNonDFS'))

def get_dn_retrycache(xbeans,hostsource,epoch_time):
	pointer_id = get_metricscategory_position(xbeans, 'Hadoop:service=DataNode,name=RetryCache.DataNodeRetryCache')
	print hostsource+" dn_retrycache_CacheHit "+str(epoch_time)+" "+str(xbeans[pointer_id].get('CacheHit'))
	print hostsource+" dn_retrycache_CacheCleared "+str(epoch_time)+" "+str(xbeans[pointer_id].get('CacheCleared'))
	print hostsource+" dn_retrycache_CacheUpdated "+str(epoch_time)+" "+str(xbeans[pointer_id].get('CacheUpdated'))

def get_dn_activity(xbeans,hostsource,epoch_time):
	pointer_id = get_metricscategory_position(xbeans, 'Hadoop:service=DataNode,name=DataNodeActivity-'+str(hostsource)+'-50010')
	print hostsource+" dn_activity_BytesWritten "+str(epoch_time)+" "+str(xbeans[pointer_id].get('BytesWritten'))
	print hostsource+" dn_activity_TotalWriteTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('TotalWriteTime'))
	print hostsource+" dn_activity_BytesRead "+str(epoch_time)+" "+str(xbeans[pointer_id].get('BytesRead'))
	print hostsource+" dn_activity_TotalReadTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('TotalReadTime'))
	print hostsource+" dn_activity_BlocksWritten "+str(epoch_time)+" "+str(xbeans[pointer_id].get('BlocksWritten'))
	print hostsource+" dn_activity_BlocksRead "+str(epoch_time)+" "+str(xbeans[pointer_id].get('BlocksRead'))
	print hostsource+" dn_activity_BlocksReplicated "+str(epoch_time)+" "+str(xbeans[pointer_id].get('BlocksReplicated'))
	print hostsource+" dn_activity_BlocksRemoved "+str(epoch_time)+" "+str(xbeans[pointer_id].get('BlocksRemoved'))
	print hostsource+" dn_activity_BlocksVerified "+str(epoch_time)+" "+str(xbeans[pointer_id].get('BlocksVerified'))
	print hostsource+" dn_activity_BlockVerificationFailures "+str(epoch_time)+" "+str(xbeans[pointer_id].get('BlockVerificationFailures'))
	print hostsource+" dn_activity_BlocksCached "+str(epoch_time)+" "+str(xbeans[pointer_id].get('BlocksCached'))
	print hostsource+" dn_activity_BlocksUncached "+str(epoch_time)+" "+str(xbeans[pointer_id].get('BlocksUncached'))
	print hostsource+" dn_activity_ReadsFromLocalClient "+str(epoch_time)+" "+str(xbeans[pointer_id].get('ReadsFromLocalClient'))
	print hostsource+" dn_activity_ReadsFromRemoteClient "+str(epoch_time)+" "+str(xbeans[pointer_id].get('ReadsFromRemoteClient'))
	print hostsource+" dn_activity_WritesFromLocalClient "+str(epoch_time)+" "+str(xbeans[pointer_id].get('WritesFromLocalClient'))
	print hostsource+" dn_activity_WritesFromRemoteClient "+str(epoch_time)+" "+str(xbeans[pointer_id].get('WritesFromRemoteClient'))
	print hostsource+" dn_activity_BlocksGetLocalPathInfo "+str(epoch_time)+" "+str(xbeans[pointer_id].get('BlocksGetLocalPathInfo'))
	print hostsource+" dn_activity_RemoteBytesRead "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RemoteBytesRead'))
	print hostsource+" dn_activity_RemoteBytesWritten "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RemoteBytesWritten'))
	print hostsource+" dn_activity_RamDiskBlocksWrite "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RamDiskBlocksWrite'))
	print hostsource+" dn_activity_RamDiskBlocksWriteFallback "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RamDiskBlocksWriteFallback'))
	print hostsource+" dn_activity_RamDiskBytesWrite "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RamDiskBytesWrite'))
	print hostsource+" dn_activity_RamDiskBlocksReadHits "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RamDiskBlocksReadHits'))
	print hostsource+" dn_activity_RamDiskBlocksEvicted "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RamDiskBlocksEvicted'))
	print hostsource+" dn_activity_RamDiskBlocksEvictedWithoutRead "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RamDiskBlocksEvictedWithoutRead'))
	print hostsource+" dn_activity_RamDiskBlocksEvictionWindowMsNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RamDiskBlocksEvictionWindowMsNumOps'))
	print hostsource+" dn_activity_RamDiskBlocksEvictionWindowMsAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RamDiskBlocksEvictionWindowMsAvgTime'))
	print hostsource+" dn_activity_RamDiskBlocksLazyPersisted "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RamDiskBlocksLazyPersisted'))
	print hostsource+" dn_activity_RamDiskBlocksDeletedBeforeLazyPersisted "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RamDiskBlocksDeletedBeforeLazyPersisted'))
	print hostsource+" dn_activity_RamDiskBytesLazyPersisted "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RamDiskBytesLazyPersisted'))
	print hostsource+" dn_activity_RamDiskBlocksLazyPersistWindowMsNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RamDiskBlocksLazyPersistWindowMsNumOps'))
	print hostsource+" dn_activity_RamDiskBlocksLazyPersistWindowMsAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('RamDiskBlocksLazyPersistWindowMsAvgTime'))
	print hostsource+" dn_activity_FsyncCount "+str(epoch_time)+" "+str(xbeans[pointer_id].get('FsyncCount'))
	print hostsource+" dn_activity_VolumeFailures "+str(epoch_time)+" "+str(xbeans[pointer_id].get('VolumeFailures'))
	print hostsource+" dn_activity_DatanodeNetworkErrors "+str(epoch_time)+" "+str(xbeans[pointer_id].get('DatanodeNetworkErrors'))
	print hostsource+" dn_activity_ReadBlockOpNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('ReadBlockOpNumOps'))
	print hostsource+" dn_activity_ReadBlockOpAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('ReadBlockOpAvgTime'))
	print hostsource+" dn_activity_WriteBlockOpNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('WriteBlockOpNumOps'))
	print hostsource+" dn_activity_WriteBlockOpAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('WriteBlockOpAvgTime'))
	print hostsource+" dn_activity_BlockChecksumOpNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('BlockChecksumOpNumOps'))
	print hostsource+" dn_activity_BlockChecksumOpAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('BlockChecksumOpAvgTime'))
	print hostsource+" dn_activity_CopyBlockOpNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('CopyBlockOpNumOps'))
	print hostsource+" dn_activity_CopyBlockOpAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('CopyBlockOpAvgTime'))
	print hostsource+" dn_activity_ReplaceBlockOpNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('ReplaceBlockOpNumOps'))
	print hostsource+" dn_activity_ReplaceBlockOpAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('ReplaceBlockOpAvgTime'))
	print hostsource+" dn_activity_HeartbeatsNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('HeartbeatsNumOps'))
	print hostsource+" dn_activity_HeartbeatsAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('HeartbeatsAvgTime'))
	print hostsource+" dn_activity_BlockReportsNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('BlockReportsNumOps'))
	print hostsource+" dn_activity_BlockReportsAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('BlockReportsAvgTime'))
	print hostsource+" dn_activity_IncrementalBlockReportsNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('IncrementalBlockReportsNumOps'))
	print hostsource+" dn_activity_IncrementalBlockReportsAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('IncrementalBlockReportsAvgTime'))
	print hostsource+" dn_activity_CacheReportsNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('CacheReportsNumOps'))
	print hostsource+" dn_activity_CacheReportsAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('CacheReportsAvgTime'))
	print hostsource+" dn_activity_PacketAckRoundTripTimeNanosNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('PacketAckRoundTripTimeNanosNumOps'))
	print hostsource+" dn_activity_PacketAckRoundTripTimeNanosAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('PacketAckRoundTripTimeNanosAvgTime'))
	print hostsource+" dn_activity_FlushNanosNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('FlushNanosNumOps'))
	print hostsource+" dn_activity_FlushNanosAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('FlushNanosAvgTime'))
	print hostsource+" dn_activity_FsyncNanosNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('FsyncNanosNumOps'))
	print hostsource+" dn_activity_FsyncNanosAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('FsyncNanosAvgTime'))
	print hostsource+" dn_activity_SendDataPacketBlockedOnNetworkNanosNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('SendDataPacketBlockedOnNetworkNanosNumOps'))
	print hostsource+" dn_activity_SendDataPacketBlockedOnNetworkNanosAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('SendDataPacketBlockedOnNetworkNanosAvgTime'))
	print hostsource+" dn_activity_SendDataPacketTransferNanosNumOps "+str(epoch_time)+" "+str(xbeans[pointer_id].get('SendDataPacketTransferNanosNumOps'))
	print hostsource+" dn_activity_SendDataPacketTransferNanosAvgTime "+str(epoch_time)+" "+str(xbeans[pointer_id].get('SendDataPacketTransferNanosAvgTime'))
