import minibig_jmx_engine as mje

def get_rpc(jsonbeansdata,hostsource,epoch_time):
    pointer_id = get_metricscategory_position(jsonbeansdata, 'Hadoop:service=NameNode,name=RpcActivityForPort8020')
    print hostsource+" rpc_SentBytes "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('SentBytes'))
    print hostsource+" rpc_ReceivedBytes "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ReceivedBytes'))
    print hostsource+" rpc_RpcQueueTimeNumOps "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('RpcQueueTimeNumOps'))
    print hostsource+" rpc_RpcQueueTimeAvgTime "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('RpcQueueTimeAvgTime'))
    print hostsource+" rpc_RpcProcessingTimeNumOps "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('RpcProcessingTimeNumOps'))
    print hostsource+" rpc_RpcProcessingTimeAvgTime "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('RpcProcessingTimeAvgTime'))
    print hostsource+" rpc_RpcAuthenticationFailures "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('RpcAuthenticationFailures'))
    print hostsource+" rpc_RpcAuthenticationSuccesses "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('RpcAuthenticationSuccesses'))
    print hostsource+" rpc_RpcAuthorizationFailures "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('RpcAuthorizationFailures'))
    print hostsource+" rpc_RpcAuthorizationSuccesses "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('RpcAuthorizationSuccesses'))
    print hostsource+" rpc_NumOpenConnections "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('NumOpenConnections'))
    print hostsource+" rpc_CallQueueLength "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('CallQueueLength'))
    pointer_id = get_metricscategory_position(jsonbeansdata, 'Hadoop:service=NameNode,name=RpcDetailedActivityForPort8020')
    print hostsource+" rpc_VersionRequestNumOps "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('VersionRequestNumOps'))
    print hostsource+" rpc_VersionRequestAvgTime "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('VersionRequestAvgTime'))
    print hostsource+" rpc_RegisterDatanodeNumOps "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('RegisterDatanodeNumOps'))
    print hostsource+" rpc_RegisterDatanodeAvgTime "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('RegisterDatanodeAvgTime'))
    print hostsource+" rpc_SendHeartbeatNumOps "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('SendHeartbeatNumOps'))
    print hostsource+" rpc_SendHeartbeatAvgTime "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('SendHeartbeatAvgTime'))
    print hostsource+" rpc_BlockReportNumOps "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('BlockReportNumOps'))
    print hostsource+" rpc_BlockReportAvgTime "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('BlockReportAvgTime'))

def get_nn_ugi(jsonbeansdata,hostsource,epoch_time):
    pointer_id = get_metricscategory_position(jsonbeansdata, 'Hadoop:service=NameNode,name=UgiMetrics')
	print hostsource+" nn_ugi_LoginSuccessNumOps "+str(epoch_time)+" "+str(jsonbeansdata[ugi_pointer_id].get('LoginSuccessNumOps'))
    print hostsource+" nn_ugi_LoginFailureNumOps "+str(epoch_time)+" "+str(jsonbeansdata[ugi_pointer_id].get('LoginFailureNumOps'))

def get_fsnamesys(jsonbeansdata,hostsource,epoch_time):
    pointer_id = get_metricscategory_position(jsonbeansdata, 'Hadoop:service=NameNode,name=FSNamesystemState')
    print hostsource+" fsnamesys_CapacityTotal "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('CapacityTotal'))
    print hostsource+" fsnamesys_CapacityUsed "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('CapacityUsed'))
    print hostsource+" fsnamesys_CapacityRemaining "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('CapacityRemaining'))
    print hostsource+" fsnamesys_TotalLoad "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('TotalLoad'))
    print hostsource+" fsnamesys_BlocksTotal "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('BlocksTotal'))
    print hostsource+" fsnamesys_MaxObjects "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('MaxObjects'))
    print hostsource+" fsnamesys_FilesTotal "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('FilesTotal'))
    print hostsource+" fsnamesys_PendingReplicationBlocks "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('PendingReplicationBlocks'))
    print hostsource+" fsnamesys_UnderReplicatedBlocks "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('UnderReplicatedBlocks'))
    print hostsource+" fsnamesys_ScheduledReplicationBlocks "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ScheduledReplicationBlocks'))
    print hostsource+" fsnamesys_PendingDeletionBlocks "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('PendingDeletionBlocks'))
    print hostsource+" fsnamesys_BlockDeletionStartTime "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('BlockDeletionStartTime'))
    print hostsource+" fsnamesys_FSState "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('FSState'))
    print hostsource+" fsnamesys_NumLiveDataNodes "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('NumLiveDataNodes'))
    print hostsource+" fsnamesys_NumDeadDataNodes "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('NumDeadDataNodes'))
    print hostsource+" fsnamesys_NumDecomLiveDataNodes "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('NumDecomLiveDataNodes'))
    print hostsource+" fsnamesys_NumDecomDeadDataNodes "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('NumDecomDeadDataNodes'))
    print hostsource+" fsnamesys_VolumeFailuresTotal "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('VolumeFailuresTotal'))
    print hostsource+" fsnamesys_EstimatedCapacityLostTotal "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('EstimatedCapacityLostTotal'))
    print hostsource+" fsnamesys_NumDecommissioningDataNodes "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('NumDecommissioningDataNodes'))
    print hostsource+" fsnamesys_NumStaleDataNodes "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('NumStaleDataNodes'))
    print hostsource+" fsnamesys_NumStaleStorages "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('NumStaleStorages'))
    pointer_id = get_metricscategory_position(jsonbeansdata, 'Hadoop:service=NameNode,name=FSNamesystem')
    print hostsource+" fsnamesys_MissingBlocks "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('MissingBlocks'))
    print hostsource+" fsnamesys_MissingReplOneBlocks "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('MissingReplOneBlocks'))
    print hostsource+" fsnamesys_ExpiredHeartbeats "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ExpiredHeartbeats'))
    print hostsource+" fsnamesys_TransactionsSinceLastCheckpoint "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('TransactionsSinceLastCheckpoint'))
    print hostsource+" fsnamesys_TransactionsSinceLastLogRoll "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('TransactionsSinceLastLogRoll'))
    print hostsource+" fsnamesys_LastCheckpointTime "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('LastCheckpointTime'))
    print hostsource+" fsnamesys_CapacityTotalGB "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('CapacityTotalGB'))
    print hostsource+" fsnamesys_CapacityUsedGB "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('CapacityUsedGB'))
    print hostsource+" fsnamesys_CapacityRemainingGB "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('CapacityRemainingGB'))
    print hostsource+" fsnamesys_CapacityUsedNonDFS "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('CapacityUsedNonDFS'))

def get_retrycache(jsonbeansdata,hostsource,epoch_time):
    pointer_id = get_metricscategory_position(jsonbeansdata, 'Hadoop:service=NameNode,name=RetryCache.NameNodeRetryCache')
    print hostsource+" retrycache_CacheHit "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('CacheHit'))
    print hostsource+" retrycache_CacheCleared "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('CacheCleared'))
    print hostsource+" retrycache_CacheUpdated "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('CacheUpdated'))
