import minibig_jmx_engine as mje

def get_replication(jsonbeansdata,hostsource,epoch_time):
    pointer_id = mje.get_metricscategory_position(jsonbeansdata, 'Hadoop:service=HBase,name=RegionServer,sub=Replication')
    print hostsource+" replication_sink.appliedOps "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('sink.appliedOps'))
    print hostsource+" replication_sink.appliedBatches "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('sink.appliedBatches'))
    print hostsource+" replication_sink.ageOfLastAppliedOp "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('sink.ageOfLastAppliedOp'))

def get_wal(jsonbeansdata,hostsource,epoch_time):
    pointer_id = mje.get_metricscategory_position(jsonbeansdata, 'Hadoop:service=HBase,name=RegionServer,sub=WAL')
    print hostsource+" wal_rollRequest "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('rollRequest'))
    print hostsource+" wal_SyncTime_num_ops "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('SyncTime_num_ops'))
    print hostsource+" wal_SyncTime_min "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('SyncTime_min'))
    print hostsource+" wal_SyncTime_max "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('SyncTime_max'))
    print hostsource+" wal_AppendSize_num_ops "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('AppendSize_num_ops'))
    print hostsource+" wal_AppendSize_min "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('AppendSize_min'))
    print hostsource+" wal_AppendSize_max "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('AppendSize_max'))
    print hostsource+" wal_AppendTime_num_ops "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('AppendTime_num_ops'))
    print hostsource+" wal_AppendTime_min "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('AppendTime_min'))
    print hostsource+" wal_AppendTime_max "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('AppendTime_max'))
    print hostsource+" wal_slowAppendCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('slowAppendCount'))
    print hostsource+" wal_lowReplicaRollRequest "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('lowReplicaRollRequest'))
    print hostsource+" wal_appendCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('appendCount'))

def get_regionserver(jsonbeansdata,hostsource,epoch_time):
    pointer_id = mje.get_metricscategory_position(jsonbeansdata, 'Hadoop:service=HBase,name=RegionServer,sub=Server')
    print hostsource+" regionserver_regionCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('regionCount'))
    print hostsource+" regionserver_storeCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('storeCount'))
    print hostsource+" regionserver_hlogFileCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('hlogFileCount'))
    print hostsource+" regionserver_hlogFileSize "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('hlogFileSize'))
    print hostsource+" regionserver_storeFileCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('storeFileCount'))
    print hostsource+" regionserver_memStoreSize "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('memStoreSize'))
    print hostsource+" regionserver_storeFileSize "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('storeFileSize'))
    print hostsource+" regionserver_regionServerStartTime "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('regionServerStartTime'))
    print hostsource+" regionserver_totalRequestCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('totalRequestCount'))
    print hostsource+" regionserver_readRequestCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('readRequestCount'))
    print hostsource+" regionserver_writeRequestCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('writeRequestCount'))
    print hostsource+" regionserver_checkMutateFailedCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('checkMutateFailedCount'))
    print hostsource+" regionserver_checkMutatePassedCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('checkMutatePassedCount'))
    print hostsource+" regionserver_storeFileIndexSize "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('storeFileIndexSize'))
    print hostsource+" regionserver_staticIndexSize "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('staticIndexSize'))
    print hostsource+" regionserver_staticBloomSize "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('staticBloomSize'))
    print hostsource+" regionserver_mutationsWithoutWALCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('mutationsWithoutWALCount'))
    print hostsource+" regionserver_mutationsWithoutWALSize "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('mutationsWithoutWALSize'))
    print hostsource+" regionserver_percentFilesLocal "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('percentFilesLocal'))
    print hostsource+" regionserver_splitQueueLength "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('splitQueueLength'))
    print hostsource+" regionserver_compactionQueueLength "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('compactionQueueLength'))
    print hostsource+" regionserver_flushQueueLength "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('flushQueueLength'))
    print hostsource+" regionserver_blockCacheFreeSize "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('blockCacheFreeSize'))
    print hostsource+" regionserver_blockCacheCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('blockCacheCount'))
    print hostsource+" regionserver_blockCacheSize "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('blockCacheSize'))
    print hostsource+" regionserver_blockCacheHitCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('blockCacheHitCount'))
    print hostsource+" regionserver_blockCacheMissCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('blockCacheMissCount'))
    print hostsource+" regionserver_blockCacheEvictionCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('blockCacheEvictionCount'))
    print hostsource+" regionserver_blockCountHitPercent "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('blockCountHitPercent'))
    print hostsource+" regionserver_blockCacheExpressHitPercent "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('blockCacheExpressHitPercent'))
    print hostsource+" regionserver_updatesBlockedTime "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('updatesBlockedTime'))
    print hostsource+" regionserver_flushedCellsCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('flushedCellsCount'))
    print hostsource+" regionserver_compactedCellsCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('compactedCellsCount'))
    print hostsource+" regionserver_majorCompactedCellsCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('majorCompactedCellsCount'))
    print hostsource+" regionserver_flushedCellsSize "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('flushedCellsSize'))
    print hostsource+" regionserver_compactedCellsSize "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('compactedCellsSize'))
    print hostsource+" regionserver_majorCompactedCellsSize "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('majorCompactedCellsSize'))
    print hostsource+" regionserver_blockedRequestCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('blockedRequestCount'))
    print hostsource+" regionserver_splitSuccessCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('splitSuccessCount'))
    print hostsource+" regionserver_splitRequestCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('splitRequestCount'))
    print hostsource+" regionserver_Append_num_ops "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('Append_num_ops'))
    print hostsource+" regionserver_Delete_num_ops "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('Delete_num_ops'))
    print hostsource+" regionserver_Mutate_num_ops "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('Mutate_num_ops'))
    print hostsource+" regionserver_ScanNext_num_ops "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('ScanNext_num_ops'))
    print hostsource+" regionserver_slowDeleteCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('slowDeleteCount'))
    print hostsource+" regionserver_slowIncrementCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('slowIncrementCount'))
    print hostsource+" regionserver_FlushTime_num_ops "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('FlushTime_num_ops'))
    print hostsource+" regionserver_Get_num_ops "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('Get_num_ops'))
    print hostsource+" regionserver_Replay_num_ops "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('Replay_num_ops'))
    print hostsource+" regionserver_slowGetCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('slowGetCount'))
    print hostsource+" regionserver_slowAppendCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('slowAppendCount'))
    print hostsource+" regionserver_slowPutCount "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('slowPutCount'))
    print hostsource+" regionserver_SplitTime_num_ops "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('SplitTime_num_ops'))
    print hostsource+" regionserver_Increment_num_ops "+str(epoch_time)+" "+str(jsonbeansdata[pointer_id].get('Increment_num_ops'))
